### ISSUE TITLE
Which files do we want to keep?

### ISSUE THREAD

**Issue by rogerssam** [IBS-AR/archive#1]
@emitanaka @garthtarr @pitakakariki 

As per email chain, there are probably several folders/document that I think we don't need to worry about backing up/archiving. Hans is possibly adding more which I will add if necessary.

Some specific examples:

- [x] Scholarship application forms since 2008: [here](https://github.com/IBS-AR/old_website/tree/main/awards) and [here](https://github.com/IBS-AR/old_website/tree/main/docs)
- [x] [2011 Conference Abstract template and timeline](https://github.com/IBS-AR/old_website/tree/main/Conf_Docs)
- [x] [IBC Travel Grant forms since 2010](https://github.com/IBS-AR/old_website/tree/main/docs)
- [x] [Mario D’Antuono’s ‘Biometrical Methods for the Agricultural Sciences’ book/page from 2014](https://github.com/IBS-AR/old_website/tree/main/MarioZ)
- [x] [Profiles and photos of Rachel Fewster, Scott Foster, Kaye Basford and Kevin Wang from 2008.](https://github.com/IBS-AR/old_website/tree/main/member)
- [x] [Newsletters are all on the new site already, do we need them duplicated on the old one?](https://github.com/IBS-AR/old_website/tree/main/newsletters)
- [x] [Past conference sites (we have websites/pages from 2011, and talks from 2009) as separate sub-sites or just within the current page as they currently are?](https://github.com/IBS-AR/old_website/tree/main/conferences)

Feel free to have an explore and have a look at what else is there. I believe there are numerous html pages that are excess to requirement, but I think we just leave them as is and don't worry about them.

"Who cares, just keep it all" is also a valid opinion 😁

**Comment by rogerssam** [comment]
@emitanaka, @pitakakariki, @garthtarr Any suggestions on the above?

**Comment by emitanaka** [comment]
Thanks for the bump up Sam! 

I've gone through some of the files but none of them seem to be of a concern privacy-wise. In that sense, I'm inclined to keep them all.

Regarding the past conferences, I'd probably leave it as it is to ensure all the existing (relative) links work. Thanks for curating these! It's nice that it seems to all work from my local drive (including the conference booklet links).

For going forward, shall we rename this repo as "archive"? Then the link for the old website will be ibs-ar.github.io/archive (or if we port ibs-ar.github.io to biometrics.org.au, we could use the sub-website like "archive.biometrics.org.au"). We will need to make this repo public for GitHub Pages to work.

**Comment by rogerssam** [comment]
Thanks Emi. Yes, my plan is to make this a sub domain like archive.biometricsociety.org.au, so ~I'll rename~ I've renamed the repo. 
We will need a public repo, but just wanted to check we weren't exposing anything we shouldn't first.

**Comment by emitanaka** [comment]
You are right to be concerned. I did sample the ones that are most likely to be the suspect of possible privacy issues (e.g. folder called MarioZ, member, membership) but none of them caused alarm. If all these files were on the website then it would have been exposed to the public before, so it makes sense that nothing particularly alarming would be on it. In that sense, I think it's safe to make it public.

**Comment by rogerssam** [comment]
Website is live, and seems to be a reasonable approximation of the old site so I'll close this.

**Comment by garthtarr** [comment]
Nice work!
